name: Bryan Holman
description:
meta_description: "Bryan Holman"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://bhlmn.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://bhlmn.github.io'
author:         'Bryan Holman'
