# Setup
title:            Bryan Holman
tagline:          ''
description:      "I'm a Ph. D. candidate at the Florida Institute of Technology. I watch clouds, play with my kids, code in R and python, & study machine learning and data science."

author:
  name:           'Bryan Holman'
  url:            https://bhlmn.github.io

github:
  repo:           https://github.com/bhlmn

theme: jekyll-theme-minimal
